# Generated by Django 4.2.7 on 2025-04-27 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_vote_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 8, 52, 39, 786378, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
