# Generated by Django 4.2.7 on 2025-04-29 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 6, 16, 59, 918644, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
