# Generated by Django 4.2.7 on 2025-05-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 10, 30, 51, 26331, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
